version: "3.9"

services:
  app:
    build: ./app
    expose:
      - "3000"
    networks:
      proxy_net:
        ipv4_address: 172.25.0.5

  nginx1:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx1.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      proxy_net:
        ipv4_address: 172.25.0.2
    restart: unless-stopped

  nginx2:
    image: nginx:1.25-alpine
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      proxy_net:
        ipv4_address: 172.25.0.3
    restart: unless-stopped

  nginx3:
    image: nginx:1.25-alpine
    ports:
      - "82:80"
    volumes:
      - ./nginx/nginx3.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      proxy_net:
        ipv4_address: 172.25.0.4
    restart: unless-stopped

networks:
  proxy_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
