events {}

http {
    # Внешний сервер (порт 80) – только на своём IP 172.25.0.2
    server {
        listen 172.25.0.2:80;

        location /nginx2/ {
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_pass http://nginx2:8080/;
        }
        location /nginx3/ {
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_pass http://nginx3:8080/;
        }
        location /app/ {
            proxy_set_header X-Forwarded-For "$remote_addr, $server_addr";
            proxy_pass http://app:3000/;
        }
    }

    # Внутренний сервер (порт 8080) – на своём IP 172.25.0.2
    server {
        listen 172.25.0.2:8080;

        location /nginx2/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://nginx2:8080/;
        }
        location /nginx3/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://nginx3:8080/;
        }
        location /app/ {
            proxy_set_header X-Forwarded-For "$proxy_add_x_forwarded_for, $server_addr";
            proxy_pass http://app:3000/;
        }
    }
}
