events {}

http {
    # Внешний контур (Принимает запросы с хоста на порт 80)
    server {
        listen 80;

        location /nginx2/ {
            proxy_set_header X-Forwarded-For $remote_addr; # Затираем фейковый XFF
            proxy_pass http://nginx2:8080/;
        }
        location /nginx3/ {
            proxy_set_header X-Forwarded-For $remote_addr; # Затираем фейковый XFF
            proxy_pass http://nginx3:8080/;
        }
        location /app/ {
            proxy_set_header X-Forwarded-For "$remote_addr, $server_addr";
            proxy_pass http://app:3000/;
        }
    }

    # Внутренний контур (Принимает транзитный трафик от других nginx по Docker-сети)
    server {
        listen 8080;

        location /nginx2/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Наращиваем цепочку
            proxy_pass http://nginx2:8080/;
        }
        location /nginx3/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://nginx3:8080/;
        }
        location /app/ {
            proxy_set_header X-Forwarded-For "$proxy_add_x_forwarded_for, $server_addr";
            proxy_pass http://app:3000/;
        }
    }
}